import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const index = read('index.html');
const app = read('assets/app.js');
const backend = read('apps-script/Code.gs');
const favicon = read('favicon.svg');

new Function(backend);

const failures = [];
const expect = (condition, message) => { if (!condition) failures.push(message); };

expect(!/hirame|문의\s*@/i.test(index + app + backend), '원본 제작자 표기가 코드에 남아 있습니다.');
expect(!/supabase/i.test(index + app + backend), 'Supabase 의존성이 남아 있습니다.');
expect(!/setSharing\s*\(/.test(backend), '드라이브 파일 공개 공유 코드가 있습니다.');
expect(/frame-ancestors 'none'/.test(index), '클릭재킹 방지 CSP가 없습니다.');
expect(!/unsafe-inline|unsafe-eval/.test(index), 'CSP에 unsafe 설정이 있습니다.');
expect(/get_public_data/.test(backend) && /submit_signature/.test(backend), '공개 API가 누락되었습니다.');
expect(/requireAdminSession_/.test(backend), '관리자 세션 검증이 누락되었습니다.');
expect(/view:\s*'bootstrap'/.test(app), '관리자 로그인이 빠른 bootstrap 보기를 요청하지 않습니다.');
expect(/setAdminLoginMode\(false\)[\s\S]*showModal\(\)[\s\S]*get_setup_status/.test(app), '관리자 로그인 창이 초기 설정 확인보다 먼저 열리지 않습니다.');
expect(!/관리자 확인 중|확인 중…/.test(app), '관리자 로그인 버튼에 불필요한 확인 중 대기가 남아 있습니다.');
expect(/get_admin_section/.test(app + backend) && /function getAdminSection_/.test(backend), '관리자 탭별 지연 로딩 API가 누락되었습니다.');
expect(!/id="adminRefresh"|id="adminLogout"|refreshActiveAdminSection|logoutAdmin/.test(index + app), '제거하기로 한 관리자 새로고침·로그아웃 UI 또는 코드가 남아 있습니다.');
expect(!/privacyConfirm|연수 참여 확인을 위한 개인정보 처리 안내를 확인했습니다|개인정보 처리 안내를 확인해 주세요/.test(index + app), '서명 제출 전 개인정보 확인 체크 항목 또는 검증이 남아 있습니다.');
expect(/function syncRecordDateToTraining\(\)[\s\S]*training\.date[\s\S]*todaySeoul\(\)[\s\S]*recordDate[\s\S]*disabled/.test(app) && /recordTraining'\)\.addEventListener\('change', syncRecordDateToTraining\)/.test(app), '서명 기록에서 연수를 선택할 때 날짜가 자동 설정되지 않습니다.');
expect(/id="closeAdmin"[^>]*>닫기<\//.test(index) && !/id="closeAdmin"[^>]*>×<\//.test(index), '관리자 닫기 버튼이 글자 버튼으로 바뀌지 않았습니다.');
expect(!/data-admin-tab="exports"|data-admin-panel="exports"/.test(index), '독립 출력·삭제 관리자 탭이 남아 있습니다.');
expect(/data-action="toggle-export"/.test(app) && /id="trainingExportPanel"/.test(index), '연수별 펼침 출력 기능이 없습니다.');
expect(/data-action="toggle-unsigned"/.test(app) && /id="trainingUnsignedPanel"/.test(index), '연수별 미서명 현황 기능이 없습니다.');
expect(/get_training_signature_status/.test(app + backend) && /function getTrainingSignatureStatus_/.test(backend), '연수별 서명 현황 관리자 API가 없습니다.');
expect(/unsignedStatusMode:\s*'unsigned'/.test(app) && /data-unsigned-view="unsigned"/.test(index) && /data-unsigned-view="all"/.test(index), '미서명 기본 보기와 전체 현황 전환이 없습니다.');
expect(/startUnsignedStatusRefresh/.test(app) && /setInterval[\s\S]*ADMIN_SYNC_MS/.test(app), '미서명 현황의 30초 자동 갱신이 없습니다.');
expect(/outsideRosterSignedCount/.test(app + backend), '현재 명단 외 서명 건수 안내가 없습니다.');
expect(/const requestSession = state\.adminSession[\s\S]*state\.adminSession !== requestSession/.test(app), '로그아웃 뒤 늦게 도착한 미서명 현황 응답을 폐기하지 않습니다.');
const statusBody = backend.slice(backend.indexOf('function getTrainingSignatureStatus_'), backend.indexOf('function deleteRecord_'));
expect(/bool_\(person\.active\)/.test(statusBody) && /sort\(staffSort_\)/.test(statusBody), '미서명 현황이 활성 구성원 등록순을 기준으로 하지 않습니다.');
expect(/assertTrainingRequestDate_\(training, signDate, '현황'\)/.test(statusBody) && /function assertTrainingRequestDate_[\s\S]*TRAINING_DATE/.test(backend), '고정 날짜 연수의 현황 날짜를 서버에서 검증하지 않습니다.');
expect(!/imageFileId|fileId|DriveApp|getBlob/.test(statusBody), '미서명 현황 API가 서명 이미지나 Drive 파일 정보를 노출합니다.');
expect(/id="orphanExportSection"/.test(index) && /renderOrphanExportJobs/.test(app), '삭제된 연수의 출력 내역 접근 기능이 없습니다.');
expect(/training_workspace/.test(app + backend) && /trainings:[\s\S]*exports:/.test(backend), '연수·출력 작업 통합 관리자 API가 없습니다.');
expect(/let\s+shareToken\s*=/.test(app) && /function getAdminBootstrap_\([\s\S]*shareToken:\s*shareToken[\s\S]*loadedSections:\s*\['settings', 'trainings', 'share'\]/.test(backend), '관리자 전용 주소에서 메인 화면으로 복귀할 공유 키가 로그인 응답에 없습니다.');
expect(/function closeAdminAndLogout\(\)[\s\S]*currentShareToken[\s\S]*history\.replaceState[\s\S]*initializePublicApp\(\)/.test(app), '관리자 닫기 뒤 올바른 공유 메인 화면을 다시 불러오지 않습니다.');
expect(/training\.daily[\s\S]*exportDate[\s\S]*disabled/.test(app), '고정 날짜 연수와 매일 연수의 출력 날짜 처리가 없습니다.');
expect(/demo-training-2[\s\S]{0,180}daily:\s*true/.test(app), '데모에 날짜를 바꿀 수 있는 매일 연수가 없습니다.');
expect(/function closeAdminAndLogout\(\)[\s\S]*rpc\('logout'\)[\s\S]*adminSession = ''/.test(app), '관리자 닫기 시 세션 종료 처리가 없습니다.');
expect(/adminDialog'\)\.addEventListener\('cancel'/.test(app), 'Esc로 관리자 화면을 닫을 때의 로그아웃 처리가 없습니다.');
expect(/ADMIN_SYNC_MS\s*=\s*30000/.test(app), '관리자 화면의 30초 백그라운드 동기화가 누락되었습니다.');
expect(!/await\s+refreshAdminData\s*\(/.test(app), '단순 저장 뒤 전체 관리자 데이터를 다시 읽고 있습니다.');
expect(/pendingTraining/.test(app) && /state\.adminData\.trainings = previousTrainings/.test(app), '연수 저장의 즉시 화면 반영 또는 실패 복구가 누락되었습니다.');
expect(/REQUEST_CONTEXT_/.test(backend) && /context\.spreadsheet/.test(backend) && /context\.rows/.test(backend), 'Apps Script 요청 범위 시트·행 캐시가 누락되었습니다.');
const loginBody = backend.slice(backend.indexOf('function adminLogin_'), backend.indexOf('function createAdminLoginResult_'));
expect(!/cleanupStaleExportJobs/.test(loginBody), '관리자 로그인 중 오래된 출력 작업 정리가 실행됩니다.');
expect(/created\.length, SHEETS\.STAFF\.headers\.length\)[\s\S]*setValues/.test(backend), '구성원 일괄 등록이 범위 단위로 저장되지 않습니다.');
expect(/withAdminMutationLock_/.test(backend), '동시 관리자 수정 잠금이 누락되었습니다.');
expect(/\^\\d\{4\}\$/.test(backend), '숫자 4자리 관리자 비밀번호 검증이 누락되었습니다.');
expect(!/privacyContact|settingsPrivacyContact/.test(index + app + backend), '개인정보 담당자·연락처 항목이 남아 있습니다.');
expect(!/trainingTarget/.test(index + app), '연수 대상·내용 입력 항목이 남아 있습니다.');
expect(!/training\.target/.test(app), '연수 카드가 대상·내용 값을 사용하고 있습니다.');
expect(/headers:\s*\['id', 'title', 'target',[^\]]*'audienceMode', 'audienceDepartments'(?:,\s*'onsiteCodeRequired')?\]/.test(backend), '연수별 서명 대상 부서 저장 열이 없습니다.');
expect(/id="trainingAudienceAll"/.test(index) && /id="trainingAudienceDepartments"/.test(index) && /id="trainingDepartmentChoices"/.test(index), '관리자 연수 폼의 전체 구성원·부서 선택 UI가 없습니다.');
expect(/function trainingTargetsStaff_/.test(backend) && /STAFF_NOT_TARGET/.test(backend), '서버가 연수별 대상 부서를 제출 시 재검증하지 않습니다.');
expect(/function trainingAudienceMode_\(training\)[\s\S]*return 'invalid'/.test(backend) && /mode !== 'departments'\) return false/.test(backend), '손상된 연수 대상 설정이 전체 구성원으로 확대될 수 있습니다.');
expect(/trainingRows\.some\(function\(training\)[\s\S]*trainingTargetsStaff_\(training, person\)/.test(backend), '공개 API가 현재 공개 연수의 대상 명단만 반환하지 않습니다.');
expect(/staffForTraining\(state\.publicData\?\.staff/.test(app) && /isStaffIncludedInTraining\(state\.selectedTraining/.test(app), '공개 이름 선택 화면이 선택한 연수의 대상 부서를 적용하지 않습니다.');
expect(/bool_\(person\.active\) && trainingTargetsStaff_\(training, person\)/.test(statusBody), '미서명 현황이 연수별 대상 부서를 적용하지 않습니다.');
expect(/buildExportRoster_[\s\S]*bool_\(person\.active\) && trainingTargetsStaff_\(training, person\)/.test(backend), '출력 명단이 연수별 대상 부서를 적용하지 않습니다.');
expect(/signatureSnapshot:\s*JSON\.stringify\(roster\.map/.test(backend), '출력에 포함되지 않은 대상 외 서명이 원본 삭제 스냅샷에 들어갈 수 있습니다.');
expect(/rename_department[\s\S]*연수 대상/.test(backend) && /changedTrainings/.test(backend), '부서명 일괄 변경이 연수별 대상 부서명을 함께 갱신하지 않습니다.');
expect(!/올바른 공유 링크가 아닙니다/.test(index + app), '공개 첫 화면에 잘못된 링크 오류 문구가 남아 있습니다.');
expect(!/서명 화면을 열 수 없습니다/.test(index + app), '연수가 없을 때 오류 중심 문구가 남아 있습니다.');
expect(/오늘 참여할 수 있는 연수가 없습니다/.test(index), '연수가 없을 때의 안내 문구가 없습니다.');
expect(/날짜·시간·활성 상태/.test(index), '연수가 없을 때 관리자 확인 안내가 없습니다.');
expect(/rel="icon"[^>]+favicon\.svg/.test(index), '브라우저 파비콘 연결이 없습니다.');
expect(/id="faviconLink"/.test(index) && /faviconLink\.href = faviconUrl/.test(app), '공개 설정에 따른 동적 파비콘 적용이 없습니다.');
expect(/href="favicon\.svg\?v=20260720\.5"/.test(index) && /DEFAULT_FAVICON_URL = 'favicon\.svg\?v=20260720\.5'/.test(app), '기본 파비콘 캐시 버전이 화면과 스크립트에서 일치하지 않습니다.');
expect(/<title[^>]*>연수 전자서명<\/title>/.test(favicon), '기본 파비콘에 용도를 설명하는 제목이 없습니다.');
expect(/id="brand-tile"/.test(favicon) && /id="pen-symbol"/.test(favicon) && /id="signature-label"/.test(favicon) && />서명<\/text>/.test(favicon), '기본 파비콘이 펜 모양과 서명 글자를 함께 보여주지 않습니다.');
expect(/id="staffNames"[^>]*placeholder="띄어쓰기·쉼표·줄바꿈으로 여러 명 구분"/.test(index), '구성원 연속 입력 안내가 없습니다.');
expect(/compositionstart/.test(app) && /compositionend/.test(app) && /normalizeNameEntryText/.test(app), '한글 조합을 보호하는 구성원 입력 정리가 없습니다.');
expect(/id="settingsFaviconFile"[^>]*accept="image\/png,image\/jpeg,image\/webp/.test(index), '관리자 파비콘 이미지 선택기가 없습니다.');
expect(/FAVICON_MAX_SOURCE_BYTES\s*=\s*2 \* 1024 \* 1024/.test(app) && /FAVICON_MAX_PNG_BYTES\s*=\s*32 \* 1024/.test(app), '파비콘 브라우저 크기 제한이 없습니다.');
expect(/settings\.faviconData = input && Object\.prototype\.hasOwnProperty/.test(backend), '구버전 화면 저장 시 기존 파비콘 보존 처리가 없습니다.');
expect(/function validateFaviconData_/.test(backend) && /pngUint32_\(bytes, 16\) !== 64/.test(backend) && /bytes\.length > 32 \* 1024/.test(backend), '서버 파비콘 PNG·64×64·32KB 검증이 없습니다.');
expect(!/localStorage[^\n]*favicon|favicon[^\n]*localStorage/i.test(app), '파비콘이 브라우저 저장공간에 보관됩니다.');
expect(/id="brandMarkIcon"[^>]+src="favicon\.svg\?v=20260720\.5"/.test(index), '학교 이름 왼쪽에 기본 파비콘 이미지가 연결되지 않았습니다.');
expect(/const faviconUrl = favicon \|\| DEFAULT_FAVICON_URL/.test(app) && /\$\('brandMarkIcon'\)\.src = faviconUrl/.test(app), '파비콘 변경이 학교 이름 왼쪽 아이콘과 동기화되지 않습니다.');
expect(/브라우저 탭과 학교 이름 왼쪽에 함께 표시됩니다/.test(index), '관리자 파비콘 표시 위치 안내가 실제 동작과 다릅니다.');
expect(/section === 'settings'[\s\S]{0,140}applySettings\(state\.adminData\.settings \|\| \{\}\)/.test(app), '다른 관리자에게서 동기화된 파비콘이 메인 화면에 반영되지 않습니다.');
expect(/\.brand-mark-icon\s*\{[^}]*width:\s*100%[^}]*height:\s*100%[^}]*object-fit:\s*contain/.test(read('assets/styles.css')), '학교 이름 왼쪽 파비콘의 맞춤 표시 규칙이 없습니다.');
expect(/id="schoolDate"/.test(index) && /formatKoreanHeaderDate/.test(app), '메인 화면 날짜 표시가 없습니다.');
expect(/data-panel="trainingPanel"[\s\S]*overflow:\s*hidden/.test(read('assets/styles.css')), '첫 단계 한 화면 배치 규칙이 없습니다.');
expect(/isTrainingPublicOnDate_\(row, today\)/.test(backend) && /trainingDate <= today/.test(backend), '활성화한 과거 고정 연수가 공개 목록에 포함되지 않습니다.');
expect(/trainingDate > today[\s\S]*TRAINING_DATE/.test(backend) && /trainingDate < today\) return/.test(backend), '미래 연수 차단 또는 과거 연수 재수합 규칙이 없습니다.');
expect(/signatureMatchesTrainingDate_\(row, freshTraining, date\)/.test(backend), '고정 연수의 날짜가 지난 뒤 중복 제출을 막지 못합니다.');
expect(/signDate:\s*date,\s*signTime:\s*time/.test(backend) && /createdAt:\s*now\.toISOString\(\),\s*scopeDate:\s*scopeDate/.test(backend), '실제 제출 날짜·시각과 연수 기준일이 함께 보존되지 않습니다.');
expect(/state\.selectedTraining\.daily[\s\S]*state\.selectedTraining\.date[\s\S]*localDuplicateKey/.test(app), '브라우저 중복 키가 고정 연수와 매일 연수의 날짜 범위를 구분하지 않습니다.');
expect(/signature\.scopeDate \|\| signature\.signDate/.test(backend) && /trainingScopeDate_/.test(backend), '연수 방식 변경 시 다른 날짜의 서명이 섞이지 않도록 기준일을 구분하지 않습니다.');
expect(/signatureSnapshot:\s*JSON\.stringify/.test(backend) && /parseSignatureSnapshot_/.test(backend), '출력 뒤 추가된 서명을 원본 삭제에서 보호하는 출력 스냅샷이 없습니다.');
expect(/purge_originals'\) return withAdminMutationLock_/.test(backend), '원본 일괄 삭제가 다른 관리자 수정·제출과 직렬화되지 않습니다.');
expect(/function insertExportImageBatch_[\s\S]*원본 삭제를 막기 위해 출력을 중단/.test(backend), '서명 이미지 누락 출력이 원본 삭제 가능한 작업으로 완료될 수 있습니다.');
expect(!/지금 서명 접수 중/.test(app), '연수 카드에 불필요한 접수 상태 문구가 남아 있습니다.');
expect(/LockService/.test(backend), '동시 제출 잠금이 누락되었습니다.');
expect(/setTrashed\(true\)/.test(backend), '원본 파일 삭제 처리가 누락되었습니다.');
expect(/function onOpen\(\)/.test(backend) && /🖊️ 전자서명 관리/.test(backend), '연결형 시트 관리 메뉴가 누락되었습니다.');
expect(/TEMPLATE_LOCK/.test(backend), '배포용 원본 초기화 잠금이 누락되었습니다.');
expect(/SpreadsheetApp\.getActiveSpreadsheet\(\)/.test(backend), '학교용 사본 초기화가 현재 연결 시트를 사용하지 않습니다.');
expect(!/SpreadsheetApp\.create\(APP\.DATA_FILE\)/.test(backend), '초기화가 별도 데이터 스프레드시트를 만들고 있습니다.');
expect(/SpreadsheetApp\.openById\(PropertiesService\.getScriptProperties\(\)\.getProperty\('SPREADSHEET_ID'\)\)/.test(backend), '웹앱 데이터 접근이 저장된 시트 ID를 사용하지 않습니다.');
expect(/hideDataSheets_/.test(backend) && /사용설명서/.test(backend), '사용설명서 표시·데이터 탭 숨김 처리가 누락되었습니다.');
expect(/학교 연수 전자서명 시스템 사용설명서/.test(backend) && /training-sign-template/.test(backend), '다른 학교용 배포 사용설명서 또는 템플릿 저장소 안내가 누락되었습니다.');
expect(/https:\/\/github\.com\/school-training-sign\/training-sign-template/.test(backend), '배포 템플릿 저장소 주소가 새 조직명과 일치하지 않습니다.');
expect(!/jyejye-school/.test(backend), 'Apps Script 코드에 이전 GitHub 조직명이 남아 있습니다.');
expect(/현재 운영 시트에는 학교 데이터가 있으므로 다른 학교에 공유하지 마세요/.test(backend), '운영 시트를 배포용 원본으로 잘못 공유하지 않도록 하는 경고가 없습니다.');
expect(/getMaxRows\(\)[\s\S]*getMaxColumns\(\)[\s\S]*breakApart/.test(backend), '사용설명서 재생성 시 기존 병합 셀을 안전하게 해제하지 않습니다.');
expect(!/PDF와 XLSX가 모두 생성/.test(backend), '사용설명서에 이전 출력·삭제 조건이 남아 있습니다.');
expect(/setProperties\(secrets, false\)/.test(backend), '재초기화가 기존 Script Properties를 보존하지 않습니다.');
expect(/outputType/.test(index + app + backend) && /previewFileId/.test(backend), '선택 출력 형식 또는 비공개 미리보기 작업 정보가 누락되었습니다.');
expect(/pagenum=CENTER/.test(backend), 'PDF 페이지 번호가 가운데에 표시되도록 설정되지 않았습니다.');
expect(/base \+ 1,\s*rowsPerBlock,\s*1\)[\s\S]*?\.setWrap\(true\)/.test(backend), '긴 부서명이 출력에서 잘리지 않도록 줄바꿈 처리되지 않았습니다.');
expect(/EXPORT_BATCH_SIZE:\s*30/.test(backend) && /DOWNLOAD_CHUNK_SIZE:\s*1024 \* 1024/.test(backend), '출력 이미지 또는 파일 조각 크기 최적화가 없습니다.');
expect(/insertSheet\('_IMAGES'\)/.test(backend) && /getSheetByName\('_DATA'\)/.test(backend), '새 출력 이미지 목록 또는 기존 출력 작업 호환 처리가 없습니다.');
expect(/UrlFetchApp\.fetchAll/.test(backend) && /alt=media/.test(backend), '비공개 Drive 서명 이미지의 묶음 수신이 없습니다.');
expect(/acquireExportLease_/.test(backend) && /EXPORT_LEASE_/.test(backend) && /releaseExportLease_/.test(backend), '같은 출력 작업의 동시 처리를 막는 임시 잠금이 없습니다.');
expect(/EXPORT_LEASE_MS:\s*7 \* 60 \* 1000/.test(backend) && /exportJobIsTerminal_\(initialJob\)/.test(backend), '출력 잠금 만료 또는 완료 작업의 빠른 반환 처리가 없습니다.');
expect(/canResume/.test(app + backend) && /job\.status === 'failed' \? '다시 시도'/.test(app), '실패한 임시 출력 작업을 다시 시도할 수 없습니다.');
const previewBody = backend.slice(backend.indexOf('function createExportPreview_'), backend.indexOf('function removeExportHelperSheets_'));
expect(previewBody.indexOf('exportSpreadsheetBlob_') < previewBody.indexOf('removeExportHelperSheets_'), 'PDF 생성 성공 전에 출력 보조 시트를 삭제합니다.');
expect(/출력 미리보기 감사 기록 실패/.test(previewBody), '감사 기록 실패가 완성된 미리보기 작업을 실패로 되돌릴 수 있습니다.');
expect(/Range:\s*'bytes='/.test(backend), '출력 파일을 필요한 범위만 내려받는 처리가 없습니다.');
expect(/normalizeDriveDownloadResponse_/.test(backend) && /Content-Range/.test(backend) && /start \+ bytes\.length/.test(backend), 'Range 응답의 실제 길이와 다음 위치를 검증하지 않습니다.');
expect(/getDriveDownloadMetadata_/.test(backend) && /CacheService\.getScriptCache/.test(backend), '출력 파일 메타데이터를 조각마다 다시 조회합니다.');
expect(/해당 연수는 ' \+ trainingDate \+ '만 출력/.test(backend), '고정 날짜 연수의 출력 날짜를 서버에서 검증하지 않습니다.');
expect(/setRichTextValues/.test(backend) && /setRowHeights/.test(backend), '출력 표가 범위 단위로 작성되지 않습니다.');
expect(!/sheet\.getRange\(position\.row/.test(backend) && !/setRowHeight\(position\.row/.test(backend), '출력 표를 구성원마다 시트에 쓰는 느린 경로가 남아 있습니다.');
expect(!/Utilities\.sleep\(1000\)/.test(backend), 'PDF 생성 전에 고정 1초 대기가 남아 있습니다.');
expect(/prepareExportPreviewLoading\(training, payload\)[\s\S]*rpc\('start_export'/.test(app), '출력 요청 전에 미리보기 진행 화면이 열리지 않습니다.');
expect(/EXPORT_PREVIEW_PHASES\s*=\s*\['table', 'images', 'pdf', 'loading'\]/.test(app), '미리보기 생성 단계 표시가 없습니다.');
expect(/chunkSize:\s*1048576/.test(app), '브라우저 미리보기 다운로드가 1MB 조각을 사용하지 않습니다.');
expect(/recordPrintOpened_/.test(backend) && /canPurgeExport_/.test(backend), '인쇄 기록 또는 출력별 원본 삭제 차단이 누락되었습니다.');
expect(/frame-src 'self' blob:/.test(index), '비공개 Blob PDF 미리보기 CSP가 누락되었습니다.');
expect(fs.existsSync(path.join(root, 'vendor/qrcode.js')), 'QR 라이브러리가 없습니다.');
expect(fs.existsSync(path.join(root, 'vendor/xlsx.full.min.js')), '엑셀 라이브러리가 없습니다.');
expect(read('vendor/xlsx.full.min.js').includes('0.20.3'), 'SheetJS가 고정 버전 0.20.3이 아닙니다.');

if (failures.length) {
  console.error(failures.map(message => `- ${message}`).join('\n'));
  process.exit(1);
}

console.log('정적 보안·구성 검사 통과');
